### ISSUE TITLE
Screenshots are 404

### ISSUE THREAD

**Issue by x011** [googlesamples/android-ActionBarCompat-ShareActionProvider#1]
The screenshots are 404.

**Comment by thagikura** [comment]
Thanks for the report. This is fixed internally and this GitHub repo will be reflected in the next release.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
