### ISSUE TITLE
how to send the data to other app from first app and back to the data to first app.

### ISSUE THREAD

**Issue by JineshSharma** [googlesamples/android-ActionBarCompat-ShareActionProvider#7]

**Comment by ak794** [comment]
use socket progrming

**Comment by merukoo0507** [comment]
Hi
I uploaded the app today.

I use socket to pass data to Java server.
The Java server then notifies the C server to do image processing.

You can search for keyword "socket" in the following files:

Logo-Recognition-App/Camera2Basic/Application/src/main/java/com/example/android/camera2basic/Camera2BasicFragment.java

Logo-Recognition-App/RcvImgServer/JServer.java

Logo-Recognition-App/LogoRecognitionServer/main.cpp

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
